.PHONY: run dev build

run:
	bun run DataCenter/server.js

dev:
	powershell -Command "Start-Process -NoNewWindow -WorkingDirectory DataCenter bun 'run server.js'; Set-Location Frontend; bun run dev"

build:
	cd Frontend && bun run build

frontend:
	cd Frontend && bun run dev
